// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form2.h"
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
this->color((Fl_Color)205);
this->labelcolor((Fl_Color)253);
{ new Fl_Button(65, 190, 70, 25, "list");
} // Fl_Button* o
{ Fl_Text_Display* o = new Fl_Text_Display(145, 75, 145, 325, "dis");
  o->color(FL_RED);
  o->selection_color((Fl_Color)87);
  o->labeltype(FL_NO_LABEL);
} // Fl_Text_Display* o
{ new Fl_Button(65, 5, 70, 25, "path");
} // Fl_Button* o
{ new Fl_Input(210, 5, 580, 25, "pathin");
} // Fl_Input* o
{ new Fl_Button(65, 75, 70, 35, "Folder");
} // Fl_Button* o
{ new Fl_Button(65, 130, 70, 35, "file");
} // Fl_Button* o
{ Fl_Text_Editor* o = new Fl_Text_Editor(335, 75, 565, 325);
  o->color(FL_BLUE);
  o->selection_color((Fl_Color)165);
  o->labeltype(FL_NO_LABEL);
} // Fl_Text_Editor* o
{ new Fl_Input(470, 45, 75, 25, "pref");
} // Fl_Input* o
{ new Fl_Input(815, 45, 60, 25, "from");
} // Fl_Input* o
{ new Fl_Input(905, 45, 60, 25, "to");
} // Fl_Input* o
{ new Fl_Button(905, 260, 70, 40, "preview");
} // Fl_Button* o
{ new Fl_Button(905, 330, 70, 35, "go");
} // Fl_Button* o
{ new Fl_Button(905, 120, 70, 45, "show file");
} // Fl_Button* o
{ new Fl_Input(595, 45, 55, 25, "saf");
} // Fl_Input* o
{ Fl_Input_Choice* o = new Fl_Input_Choice(680, 45, 75, 25, "formate");
  o->labeltype(FL_NO_LABEL);
} // Fl_Input_Choice* o
end();
resizable(this);
}
