// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form.h"
form::form(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
this->color((Fl_Color)53);
this->labelcolor(FL_BLACK);
{ Fl_Button* o = new Fl_Button(605, 250, 100, 60, "convert");
  o->color((Fl_Color)44);
  o->labeltype(FL_ENGRAVED_LABEL);
  o->callback((Fl_Callback*)convert_cb);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(35, 105, 70, 55, "list");
  o->callback((Fl_Callback*)list_cb);
} // Fl_Button* o
{ Fl_Input* o = new Fl_Input(495, 40, 80, 25, "to");
  o->textcolor(FL_GRAY0);
} // Fl_Input* o
{ Fl_Output* o = new Fl_Output(210, 40, 90, 25, "extension");
  o->textcolor(FL_GRAY0);
} // Fl_Output* o
{ new Fl_Text_Display(140, 100, 400, 210, "datafiles");
} // Fl_Text_Display* o
{ Fl_Input* o = new Fl_Input(365, 40, 95, 25, "from");
  o->color((Fl_Color)55);
  o->selection_color((Fl_Color)134);
  o->textcolor(FL_BLACK);
} // Fl_Input* o
{ Fl_Button* o = new Fl_Button(610, 100, 80, 60, "preview");
  o->callback((Fl_Callback*)preview_cb);
} // Fl_Button* o
end();
}
